user  nginx;
worker_processes  auto;

pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format recipeaid '[INFO] $remote_addr "$request" $status $body_bytes_sent';

    access_log /var/log/nginx/access.log recipeaid;
    error_log  /dev/stderr notice;

    sendfile        on;
    keepalive_timeout  65;

    include /etc/nginx/conf.d/*.conf;
}
